apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: java-build-pipeline
  namespace: ci-cd
spec:
  params:
    - name: project
      type: string
      description: the project name on git
      default: "argocd-springboot-service"
  tasks:
    - name: maven-build
      taskRef:
        name: maven-build
      params:
        - name: revision
          value: "main"
        - name: project
          value: $(params.project)
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: docker-build
      taskRef:
        name: docker-build
      runAfter:
        - maven-build
      params:
        - name: tag
          value: $(tasks.maven-build.results.tag)
        - name: project
          value: $(params.project)
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: update-infra
      runAfter:
        - docker-build
      taskRef:
        name: update-infra
      params:
        - name: revision
          value: "main"
        - name: project
          value: $(params.project)
      workspaces:
        - name: source
          workspace: shared-workspace
  workspaces:
    - name: shared-workspace
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: maven-build
  namespace: ci-cd
spec:
  params:
    - name: project
      description: name of the image which needs to be created
      default: "argocd-springboot-service"
      type: string
    - name: revision
      description: Git revision to checkout (branch, tag, commit SHA)
      default: "main"
      type: string
  results:
    - name: tag
      description: tag of the image
  workspaces:
    - name: source
  steps:
    - name: clone
      image: alpine/git
      script: |
        cd $(workspaces.source.path)
        git clone https://github.com/davidezacchino/$(params.project).git $(workspaces.source.path)
        git checkout $(params.revision)
        IMAGE_TAG=$(git rev-parse HEAD)
        echo -n "${IMAGE_TAG}" > "$(results.tag.path)"
    - name: maven
      image: maven:3.9.9-amazoncorretto-21
      script: |
        pwd
        ls -la
        cd $(workspaces.source.path)
        mvn clean package
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: docker-build
  namespace: ci-cd
spec:
  params:
    - name: project
      description: name of the image which needs to be created
      default: "argocd-springboot-service"
      type: string
    - name: tag
      description: The name of the image to build and push
      default: ""
      type: string
  workspaces:
    - name: source
  steps:
    - name: docker-build-and-push
      image: docker:20.10-dind
      securityContext:
        privileged: true
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: docker-hub
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: docker-hub
              key: password
      script: |
        # Start the Docker daemon in the background
        dockerd --host=tcp://0.0.0.0:2375 --host=unix:///var/run/docker.sock &> /dev/null &
        for i in $(seq 1 30); do
          if docker info >/dev/null 2>&1; then
            echo "Docker is running."
            break
          fi
          echo "Waiting for Docker to start..."
          sleep 1
        done
        echo "Docker started successfully!"
        docker login -u $USERNAME -p $PASSWORD
        docker build -t docker.io/davidezacchino/$(params.project):$(params.tag) $(workspaces.source.path)
        docker push docker.io/davidezacchino/$(params.project):$(params.tag)
      volumeMounts:
        - name: docker-sock
          mountPath: /var/run
  volumes:
    - name: docker-sock
      emptyDir: { }
---
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-infra
  namespace: ci-cd
spec:
  params:
    - name: project
      description: name of the image which needs to be created
      default: "argocd-springboot-service"
      type: string
    - name: revision
      description: Git revision to checkout (branch, tag, commit SHA)
      default: "main"
      type: string
    - name: tag
      description: tag of the image
      default: ""
      type: string
  workspaces:
    - name: source
  steps:
    - name: update
      image: alpine/git
      script: |
        cd $(workspaces.source.path)
        rm -rf *
        git clone https://github.com/davidezacchino/$(params.project)-infra.git $(workspaces.source.path)
        git checkout $(params.revision)
        cd helm-chart
        sed -i "/imageTag/c\imageTag: '$(params.tag)'" values.yaml
        git add values.yaml
        git commit -m "update to version $(params.tag)"
        git push
        echo "Push succesfully done. Starting argoCd Sync"
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: java-build-pipeline-run
  namespace: ci-cd
spec:
  pipelineRef:
    name: java-build-pipeline
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce # access mode may affect how you can use this volume in parallel tasks
          resources:
            requests:
              storage: 3Gi
